#!/usr/bin/env python3
"""Render docs/INVENTORY.md from docs/enum/inventory.json.

The JSON is the single source; every count in the markdown is computed here so
the accounting cannot drift from the rows the way the hand-counted list did.
Also validates the rows against the vocabulary CLAUDE.md fixes.
"""
import json
import pathlib
from collections import Counter, defaultdict

HERE = pathlib.Path(__file__).parent
ROOT = HERE.parent.parent
DATA = HERE / "inventory.json"
OUT = ROOT / "docs" / "INVENTORY.md"

# The six product lines the pricing page sells (docs/enum/platform-docs.md §A.1),
# adopted in sol round 5. SIP and the Browser SDK are interfaces, not categories.
CATEGORIES = {"ai-agents": "AI Agents", "voice": "Voice", "messaging": "Messaging",
              "mfa": "MFA", "video": "Video", "fax": "Fax"}
TASK_GROUPS = {"call-control": "Call control", "routing": "Routing & queueing",
               "observe": "Monitoring", "governance": "Governance", "knowledge": "Knowledge",
               "tools": "Tools & integrations", "handoff": "Handoff", "other": "Other"}
KINDS = ["recipe", "build", "guide", "tool", "hold"]
STATUSES = ["verified", "written", "stub", "proposed", "hold"]
LENSES = {"ai": "AI Agents & Automation", "voice": "Voice & Call Control",
          "messaging": "Messaging & Realtime Chat", "video": "Video & WebRTC",
          "numbers-identity": "Numbers, Identity & Trust", "sip-migration": "SIP, PBX & Migration",
          "fax": "Fax"}

d = json.loads(DATA.read_text(encoding="utf-8"))
rows = d["rows"]

# ---- validate -------------------------------------------------------------
errors = []
slugs = Counter(r["slug"] for r in rows)
for s, n in slugs.items():
    if n > 1:
        errors.append(f"duplicate slug {s}")
for r in rows:
    if r["kind"] not in KINDS:
        errors.append(f"{r['slug']}: kind {r['kind']}")
    if r["status"] not in STATUSES:
        errors.append(f"{r['slug']}: status {r['status']}")
    if (r["kind"] == "hold") != (r["status"] == "hold"):
        errors.append(f"{r['slug']}: kind/status hold mismatch")
    if not r["products"] or r["products"][0] not in CATEGORIES:
        errors.append(f"{r['slug']}: products {r['products']}")
    if r["kind"] != "build" and r["kind"] != "hold" and r["task_group"] not in TASK_GROUPS:
        errors.append(f"{r['slug']}: task_group {r['task_group']}")
    if r["kind"] == "build" and r["task_group"] is not None:
        errors.append(f"{r['slug']}: builds carry no task group")
    if r["lens"] not in LENSES:
        errors.append(f"{r['slug']}: lens {r['lens']}")
    if not r["claim"].endswith("."):
        errors.append(f"{r['slug']}: claim is not a sentence")
    if not r["evidence"]:
        errors.append(f"{r['slug']}: no evidence")
    if r["slug"] != r["slug"].lower() or " " in r["slug"]:
        errors.append(f"{r['slug']}: slug shape")
if errors:
    raise SystemExit("inventory invalid:\n  " + "\n  ".join(errors))

# backlog ID accounting: every #1..#34 must appear in exactly one row's folds
# as a primary (first token of a fold) or be a documented kill.
KILLED = {"#7": "keep-heavy-state-out-of-global-data", "#11": "enforce-state-transitions-in-a-tool-handler",
          "#19": "keep-heavy-state-out-of-global-data"}
where = defaultdict(list)
for r in rows:
    for f in r["folds"]:
        tok = f.split()[0].rstrip(",")
        if tok.startswith("#") and tok[1:].isdigit():
            where[tok].append(r["slug"])
missing = [f"#{i}" for i in range(1, 35) if f"#{i}" not in where]
multi = {k: v for k, v in where.items() if len(v) > 1}
if missing or multi:
    raise SystemExit(f"backlog accounting: missing {missing}; in several rows {multi}")

# ---- render ---------------------------------------------------------------
def cat(r):
    return r["products"][0]

by_kind = Counter(r["kind"] for r in rows)
by_status = Counter(r["status"] for r in rows)
by_cat = Counter(cat(r) for r in rows if r["kind"] in ("recipe", "build", "hold"))
by_cat_recipe = Counter(cat(r) for r in rows if r["kind"] == "recipe")
by_lens = Counter(r["lens"] for r in rows)
launch = [r for r in rows if r.get("launch")]
needs_ver = [r for r in rows if any(e.startswith("NEEDS VERIFICATION") for e in r["evidence"])]

L = []
L.append("# Inventory — every candidate, one row each\n")
L.append("Generated from `docs/enum/inventory.json` by `docs/enum/render_inventory.py`. "
         "Do not edit this file; edit the JSON and re-render. Every count below is computed.\n")
L.append("## Counts\n")
L.append(f"**{len(rows)} rows.** By kind: " + " · ".join(f"{k} {by_kind[k]}" for k in KINDS if by_kind[k]) + ".  ")
L.append("By status: " + " · ".join(f"{s} {by_status[s]}" for s in STATUSES if by_status[s]) + ".  ")
L.append("Recipes per public category: " + " · ".join(
    f"{CATEGORIES[c]} {by_cat_recipe[c]}" for c in CATEGORIES) + ".  ")
L.append("Rows per planning lens: " + " · ".join(f"{LENSES[l]} {by_lens[l]}" for l in LENSES if by_lens[l]) + ".  ")
L.append(f"Launch set: {len(launch)}. Rows carrying a NEEDS VERIFICATION marker: {len(needs_ver)}.\n")

L.append("## Column key\n")
L.append("- **kind** recipe · build · guide (an operational workflow, or a workflow around an existing tool — nothing new to run) · tool (benchmark/harness) · hold (mechanism exists; a named blocker must clear)")
L.append("- **status** verified (runs; mechanism asserted in an artifact) · written (code exists, not verified) · stub (folder, empty entry files) · proposed (no folder) · hold")
L.append("- **category** is the first declared product (CLAUDE.md). **lens** is the seven-section planning view; it is not public.")
L.append("- **folds** are the backlog IDs (#n), scenarios, Telnyx stems (t:) and corpus slugs (c:) this row absorbs. Scenarios are tags, never rows.")
L.append("- **evidence** cites code (sdk file:line), docs (path under signalwire.com/docs/), demos (repo file:line) or FEATURES.md, or says NEEDS VERIFICATION.\n")

def render_row(r):
    tg = TASK_GROUPS.get(r["task_group"], "—") if r["task_group"] else "—"
    flag = " **·launch**" if r.get("launch") else ""
    L.append(f"### `{r['slug']}`{flag}\n")
    L.append(f"{r['claim']}\n")
    L.append(f"- kind **{r['kind']}** · status **{r['status']}** · category **{CATEGORIES[cat(r)]}** "
             f"({', '.join(r['products'])}) · task group **{tg}** · lens {LENSES[r['lens']]}")
    L.append(f"- interfaces: {', '.join(r['interfaces']) or '—'} · capabilities: {', '.join(r['capabilities']) or '—'}")
    if r["folds"]:
        L.append("- folds: " + "; ".join(r["folds"]))
    L.append("- evidence:")
    for e in r["evidence"]:
        L.append(f"  - {e}")
    L.append("")

for c in CATEGORIES:
    group = [r for r in rows if cat(r) == c and r["kind"] == "recipe"]
    L.append(f"## {CATEGORIES[c]} — {len(group)} recipes\n")
    for tg in TASK_GROUPS:
        sub = [r for r in group if r["task_group"] == tg]
        if not sub:
            continue
        L.append(f"#### {TASK_GROUPS[tg]}\n")
        for r in sub:
            render_row(r)

for kind, title in (("build", "Builds"), ("guide", "Guides"), ("tool", "Tools"), ("hold", "Holds")):
    group = [r for r in rows if r["kind"] == kind]
    L.append(f"## {title} — {len(group)}\n")
    for r in group:
        render_row(r)

L.append("## Launch set\n")
L.append("| slug | category | task group | status |\n|---|---|---|---|")
for r in launch:
    L.append(f"| `{r['slug']}` | {CATEGORIES[cat(r)]} | {TASK_GROUPS.get(r['task_group'], '—') if r['task_group'] else '—'} | {r['status']} |")
L.append("")

L.append("## Backlog ID → row\n")
L.append("| # | row |\n|---|---|")
for i in range(1, 35):
    L.append(f"| #{i} | `{where[f'#{i}'][0]}` |")
L.append("")

L.append("## Rows that need verification before they are written\n")
for r in needs_ver:
    for e in r["evidence"]:
        if e.startswith("NEEDS VERIFICATION"):
            L.append(f"- `{r['slug']}` — {e[len('NEEDS VERIFICATION:'):].strip()}")
L.append("")

OUT.write_text("\n".join(L), encoding="utf-8")
print(f"wrote {OUT} ({len(rows)} rows; launch {len(launch)}; needs verification {len(needs_ver)})")
print("kind:", dict(by_kind))
print("status:", dict(by_status))
print("recipes/category:", {CATEGORIES[c]: by_cat_recipe[c] for c in CATEGORIES})
print("lens:", {LENSES[l]: by_lens[l] for l in LENSES})
