#!/usr/bin/env python3
"""Generate recipes/README.md, the index GitHub renders when you open the folder.

Someone arriving from a recipe page lands in `recipes/`. Without this they see
a directory listing of 55 slugs and nothing else.

The index is generated rather than written, so it cannot drift from the
folders. It reads the same `recipe.json` files and the same `has_content()`
the site uses, so "written" means here exactly what it means there.

    python tools/gen_index.py           write recipes/README.md
    python tools/gen_index.py --check   exit 1 if it is out of date

The vocabulary is never hardcoded: categories and their order come from
vocab/categories/, task groups from vocab/subcategories/. A new category
appears here the moment its vocab file exists.
"""
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import build  # noqa: E402  (the site's own loader, so the two agree)

OUT = ROOT / "recipes" / "README.md"
MARK = "<!-- generated by tools/gen_index.py; edit recipe.json, not this file -->"


def rows():
    """Every folder, with the site's own notion of whether it is written."""
    out = []
    for r in build.load():
        r = dict(r)
        r["_written"] = build.has_content(r)
        out.append(r)
    return out


def render():
    V = build.V
    cats = sorted(V["categories"], key=lambda c: c.get("order", 999))
    sub_label = {k: v.get("label", k) for k, v in V.get("subcategories", {}).items()}
    all_rows = rows()
    live = [r for r in all_rows if r["_written"]]

    L = [MARK, "", "# Recipes", ""]
    L.append("Every folder here is self-contained. Clone the repository, open "
             "one, and run it.")
    L.append("")
    L.append("%d of %d folders are written and verified. The rest are planned "
             "and carry a stub." % (len(live), len(all_rows)))
    L.append("")
    L.append("Each recipe proves one claim about the platform. Its `verify.py` "
             "checks that claim")
    L.append("against the document the platform actually receives, so it runs "
             "without an account")
    L.append("and without a network.")
    L.append("")

    # a table of contents, because 55 entries is past the point of scrolling
    L.append("## Contents")
    L.append("")
    for c in cats:
        n = len([r for r in live
                 if r.get("category") == c["key"] and r.get("kind") != "build"])
        if n:
            L.append("- [%s](#%s) (%d)" % (c["label"], anchor(c["label"]), n))
    if [r for r in live if r.get("kind") == "build"]:
        L.append("- [Builds](#builds)")
    L.append("")

    for c in cats:
        got = [r for r in live
               if r.get("category") == c["key"] and r.get("kind") != "build"]
        if not got:
            continue
        L.append("## %s" % c["label"])
        L.append("")
        if c.get("blurb"):
            L.append(c["blurb"])
            L.append("")
        # inside a category, group by task group, the site's second level
        groups = {}
        for r in got:
            groups.setdefault(r.get("subcategory") or "other", []).append(r)
        for key in sorted(groups, key=lambda k: (k == "other", sub_label.get(k, k))):
            L.append("### %s" % sub_label.get(key, key))
            L.append("")
            L.append("| Recipe | What it shows | Runs as |")
            L.append("|---|---|---|")
            for r in sorted(groups[key], key=lambda r: r["title"]):
                langs = ", ".join(
                    V["surfaces"].get(s, {}).get("label", s)
                    for s in r.get("surfaces", []) if isinstance(s, str)
                ) or "-"
                L.append("| [%s](%s/) | %s | %s |"
                         % (md(r["title"]), r["slug"], md(r.get("summary", "")), langs))
            L.append("")

    builds = [r for r in live if r.get("kind") == "build"]
    if builds:
        L.append("## Builds")
        L.append("")
        L.append("A build is an application you deploy and operate, assembled "
                 "from the recipes above.")
        L.append("")
        for b in sorted(builds, key=lambda r: r["title"]):
            L.append("### [%s](%s/)" % (md(b["title"]), b["slug"]))
            L.append("")
            if b.get("summary"):
                L.append(md(b["summary"]))
                L.append("")
            comp = b.get("composes") or []
            if comp:
                L.append("Composes: " + ", ".join(
                    "[%s](%s/)" % (md(build._TITLES.get(s, s)), s) for s in comp))
                L.append("")

    planned = [r for r in all_rows if not r["_written"]]
    if planned:
        L.append("## Planned")
        L.append("")
        L.append("These folders exist and are scaffolded. They have no working "
                 "code yet.")
        L.append("")
        L.append(", ".join("`%s`" % r["slug"] for r in sorted(
            planned, key=lambda r: r["slug"])))
        L.append("")

    L.append("---")
    L.append("")
    L.append("Adding one? Read [CONTRIBUTING.md](../CONTRIBUTING.md).")
    return "\n".join(L).rstrip() + "\n"


def md(s):
    """Table cells break on a pipe, and a newline ends the row."""
    return (s or "").replace("|", "\\|").replace("\n", " ").strip()


def anchor(label):
    return "".join(ch for ch in label.lower().replace(" ", "-")
                   if ch.isalnum() or ch == "-")


def main():
    build._TITLES = {r["slug"]: r["title"] for r in build.load()}
    text = render()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("recipes/README.md is out of date; run: python tools/gen_index.py")
            return 1
        print("recipes/README.md is current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print("wrote %s (%d lines)" % (OUT.relative_to(ROOT), len(text.splitlines())))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
